# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormId',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='survey.FormId')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.OptionType')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Questions'),
        ),
    ]
