# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180211_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
